//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    public partial class BangLuong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhanVien fNhanVienID;
        [Association(@"BangLuongReferencesNhanVien")]
        public NhanVien NhanVienID
        {
            get { return fNhanVienID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVienID), ref fNhanVienID, value); }
        }
        string fnam;
        public string nam
        {
            get { return fnam; }
            set { SetPropertyValue<string>(nameof(nam), ref fnam, value); }
        }
        string fthang;
        public string thang
        {
            get { return fthang; }
            set { SetPropertyValue<string>(nameof(thang), ref fthang, value); }
        }
        DateTime fsoGio;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:HH:mm}")
]
        public DateTime soGio
        {
            get { return fsoGio; }
            set { SetPropertyValue<DateTime>(nameof(soGio), ref fsoGio, value); }
        }
        decimal fluong;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal luong
        {
            get { return fluong; }
            set { SetPropertyValue<decimal>(nameof(luong), ref fluong, value); }
        }
    }

}
