//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    public partial class ChamCong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhanVien fNhanVienID;
        [Association(@"ChamCongReferencesNhanVien")]
        public NhanVien NhanVienID
        {
            get { return fNhanVienID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVienID), ref fNhanVienID, value); }
        }
        DateTime fgioVao;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:HH:mm}")
]
        public DateTime gioVao
        {
            get { return fgioVao; }
            set { SetPropertyValue<DateTime>(nameof(gioVao), ref fgioVao, value); }
        }
        DateTime fgioRa;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:HH:mm}")
]
        public DateTime gioRa
        {
            get { return fgioRa; }
            set { SetPropertyValue<DateTime>(nameof(gioRa), ref fgioRa, value); }
        }
        public TimeSpan TongGioLamViec
        {
            get
            {
                return gioRa - gioVao;
            }
        }
        decimal fLuongMotGio;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
        public decimal LuongMotGio
        {
            get { return fLuongMotGio; }
            set { SetPropertyValue<decimal>(nameof(LuongMotGio), ref fLuongMotGio, value); }
        }

        // Calculated property for total salary
        decimal ftongLuong;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
        public decimal TongLuong
        {
            get
            {
                // Use stored field for persistence
                ftongLuong = Math.Round((decimal)TongGioLamViec.TotalHours * LuongMotGio, 2);
                return ftongLuong;
            }
            set { SetPropertyValue<decimal>(nameof(TongLuong), ref ftongLuong, value); }
        }

    }

}