//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    public partial class ChiTietNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        PhieuNhap fPhieuNhapID;
        [Association(@"ChiTietNhapReferencesPhieuNhap")]
        public PhieuNhap PhieuNhapID
        {
            get { return fPhieuNhapID; }
            set { SetPropertyValue<PhieuNhap>(nameof(PhieuNhapID), ref fPhieuNhapID, value); }
        }
        DichVu fDichVuID;
        [Association(@"ChiTietNhapReferencesDichVu")]
        public DichVu DichVuID
        {
            get { return fDichVuID; }
            set { SetPropertyValue<DichVu>(nameof(DichVuID), ref fDichVuID, value); }
        }
        double fsoLuong;
        public double soLuong
        {
            get { return fsoLuong; }
            set { SetPropertyValue<double>(nameof(soLuong), ref fsoLuong, value); }
        }
        decimal fdonGia;
        public decimal donGia
        {
            get { return fdonGia; }
            set { SetPropertyValue<decimal>(nameof(donGia), ref fdonGia, value); }
        }
    }

}
