//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    [DefaultProperty("tenDV")]
    public partial class DichVu : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ftenDV;
        public string tenDV
        {
            get { return ftenDV; }
            set { SetPropertyValue<string>(nameof(tenDV), ref ftenDV, value); }
        }
        string fdonViTinh;
        public string donViTinh
        {
            get { return fdonViTinh; }
            set { SetPropertyValue<string>(nameof(donViTinh), ref fdonViTinh, value); }
        }
        decimal fgiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal giaBan
        {
            get { return fgiaBan; }
            set { SetPropertyValue<decimal>(nameof(giaBan), ref fgiaBan, value); }
        }
        [Association(@"HoaDonCTReferencesDichVu"), Aggregated]
        public XPCollection<HoaDonCT> HoaDonCTs { get { return GetCollection<HoaDonCT>(nameof(HoaDonCTs)); } }
        [Association(@"DinhLuongReferencesDichVu"), Aggregated]
        public XPCollection<DinhLuong> DinhLuongs { get { return GetCollection<DinhLuong>(nameof(DinhLuongs)); } }
        [Association(@"ChiTietNhapReferencesDichVu"), Aggregated]
        public XPCollection<ChiTietNhap> ChiTietNhaps { get { return GetCollection<ChiTietNhap>(nameof(ChiTietNhaps)); } }
        [Association(@"TieuHaoReferencesDichVu"), Aggregated]
        public XPCollection<TieuHao> TieuHaos { get { return GetCollection<TieuHao>(nameof(TieuHaos)); } }
    }

}
