//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{
    [DefaultClassOptions]

    [DefaultProperty("soLuong")]
    public partial class HoaDonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        HoaDon fHoaDonID;
        [Association(@"HoaDonCTReferencesHoaDon")]
        public HoaDon HoaDonID
        {
            get { return fHoaDonID; }
            set { SetPropertyValue<HoaDon>(nameof(HoaDonID), ref fHoaDonID, value); }
        }
        DichVu fDichVuID;
        [Association(@"HoaDonCTReferencesDichVu")]
        public DichVu DichVuID
        {
            get { return fDichVuID; }
            set
            {
                if (SetPropertyValue<DichVu>(nameof(DichVuID), ref fDichVuID, value)
                     && !IsLoading && !IsDeleted && value != null)
                    donGia = value.giaBan;
            }
        }
        double fsoLuong;
        public double soLuong
        {
            get { return fsoLuong; }
            set { SetPropertyValue<double>(nameof(soLuong), ref fsoLuong, value); }
        }
        decimal fdonGia;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
        public decimal donGia
        {
            get { return fdonGia; }
            set { SetPropertyValue<decimal>(nameof(donGia), ref fdonGia, value); }
        }

        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]
        [PersistentAlias("ToDecimal([soLuong]) * [donGia]")]
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        public decimal thanhTien
        {
            get { return (decimal)(EvaluateAlias(nameof(thanhTien))); }
        }
        [Association(@"TieuHaoReferencesHoaDonCT"), Aggregated]
        public XPCollection<TieuHao> TieuHaos { get { return GetCollection<TieuHao>(nameof(TieuHaos)); } }
    }

}
