//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    [DefaultProperty("hoTen")]
    public partial class NhaCungCap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fhoTen;
        public string hoTen
        {
            get { return fhoTen; }
            set { SetPropertyValue<string>(nameof(hoTen), ref fhoTen, value); }
        }
        int fsoDT;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int soDT
        {
            get { return fsoDT; }
            set { SetPropertyValue<int>(nameof(soDT), ref fsoDT, value); }
        }
        int fmaSoThue;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int maSoThue
        {
            get { return fmaSoThue; }
            set { SetPropertyValue<int>(nameof(maSoThue), ref fmaSoThue, value); }
        }
        [Association(@"PhieuChiReferencesNhaCungCap"), Aggregated]
        public XPCollection<PhieuChi> PhieuChis { get { return GetCollection<PhieuChi>(nameof(PhieuChis)); } }
        [Association(@"PhieuNhapReferencesNhaCungCap"), Aggregated]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
    }

}
