//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    public partial class PhieuChi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhanVien fNhanVienID;
        [Association(@"PhieuChiReferencesNhanVien")]
        public NhanVien NhanVienID
        {
            get { return fNhanVienID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVienID), ref fNhanVienID, value); }
        }
        NhaCungCap fNhaCungCapID;
        [Association(@"PhieuChiReferencesNhaCungCap")]
        public NhaCungCap NhaCungCapID
        {
            get { return fNhaCungCapID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NhaCungCapID), ref fNhaCungCapID, value); }
        }
        int fsoPhieu;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int soPhieu
        {
            get { return fsoPhieu; }
            set { SetPropertyValue<int>(nameof(soPhieu), ref fsoPhieu, value); }
        }
        DateTime fngayChi;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")
]
        public DateTime ngayChi
        {
            get { return fngayChi; }
            set { SetPropertyValue<DateTime>(nameof(ngayChi), ref fngayChi, value); }
        }
        decimal fsoTien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal soTien
        {
            get { return fsoTien; }
            set { SetPropertyValue<decimal>(nameof(soTien), ref fsoTien, value); }
        }
    }

}
