//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLBIDA.Module.BusinessObjects.QLBIDA
{

    [DefaultProperty("soPhieu")]
    public partial class PhieuNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        NhaCungCap fNhaCungCapID;
        [Association(@"PhieuNhapReferencesNhaCungCap")]
        public NhaCungCap NhaCungCapID
        {
            get { return fNhaCungCapID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NhaCungCapID), ref fNhaCungCapID, value); }
        }
        NhanVien fNhanVienID;
        [Association(@"PhieuNhapReferencesNhanVien")]
        public NhanVien NhanVienID
        {
            get { return fNhanVienID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVienID), ref fNhanVienID, value); }
        }
        int fsoPhieu;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int soPhieu
        {
            get { return fsoPhieu; }
            set { SetPropertyValue<int>(nameof(soPhieu), ref fsoPhieu, value); }
        }
        DateTime fngayNhap;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")
]
        public DateTime ngayNhap
        {
            get { return fngayNhap; }
            set { SetPropertyValue<DateTime>(nameof(ngayNhap), ref fngayNhap, value); }
        }
        [Association(@"ChiTietNhapReferencesPhieuNhap"), Aggregated]
        public XPCollection<ChiTietNhap> ChiTietNhaps { get { return GetCollection<ChiTietNhap>(nameof(ChiTietNhaps)); } }
    }

}
